language: ruby
rvm:
  - 2.1.3

before_install:
  - sudo echo host localhost >> ~/.ssh/config
  - sudo echo   user git >> ~/.ssh/config
  - sudo echo   identityfile ~/git >> ~/.ssh/config
  - sudo echo   port 22 >> ~/.ssh/config
  - sudo echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config
  - sudo apt-get update -qq
  - sudo apt-get install -y sshpass
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - eval $(ssh-agent -s)
  - ssh-add /home/vagrant/.ssh/id_rsa
  - sudo apt-get install -y cmake libssh2* libgit2* ruby1.9.1-dev
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"

install:
  - travis_wait bundle install --path=~/.bundle --jobs=3 --retry=3 --without development production console
  - sudo apt-get install -y libaprutil1-dev swig
  - wget http://apache.parentingamerica.com/subversion/subversion-1.9.5.tar.gz
  - tar xzf subversion-1.9.5.tar.gz
  - wget http://www.sqlite.org/sqlite-amalgamation-3071501.zip
  - unzip sqlite-amalgamation-3071501.zip
  - mv sqlite-amalgamation-3071501 subversion-1.9.5/sqlite-amalgamation
  - cd subversion-1.9.5
  - LDFLAGS="-L/home/travis/.rvm/rubies/ruby-2.1.3/lib/" ./configure --prefix=/home/travis/.rvm/rubies/ruby-2.1.3/
  - make
  - make swig-rb
  - make install
  - make install-swig-rb
  - cd ..

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
  - cp config/database.yml.ci config/database.yml
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake test
  - bundle exec rspec

notifications:
  email: false

bundler_args: --retry 10

cache:
  directories:
  - ~/.bundle
