language: ruby
rvm:
  - 2.3.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libssh2-1-dev ghostscript
  - sudo apt-get install imagemagick libmagickwand-dev

install:
  - travis_wait bundle install --path=~/.bundle --jobs=3 --retry=3 --without development production console
  - sudo apt-get install -y libaprutil1-dev swig
  - wget http://www-us.apache.org/dist/subversion/subversion-1.9.7.tar.gz
  - tar xzf subversion-1.9.7.tar.gz
  - wget https://www.sqlite.org/sqlite-amalgamation-3071501.zip
  - unzip sqlite-amalgamation-3071501.zip
  - mv sqlite-amalgamation-3071501 subversion-1.9.7/sqlite-amalgamation
  - cd subversion-1.9.7
  - LDFLAGS="-L/home/travis/.rvm/rubies/ruby-2.3.1/lib/" ./configure --prefix=/home/travis/.rvm/rubies/ruby-2.3.1/
  - make
  - make swig-rb
  - make install
  - make install-swig-rb
  - cd ..

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
  - cp config/database.yml.ci config/database.yml
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake test
  - bundle exec rspec

services:
  - redis-server

notifications:
  email: false

bundler_args: --retry 10

cache:
  directories:
  - ~/.bundle
