# Read about fixtures at http://ar.rubyonrails.org/classes/Fixtures.html

# User schema template:
#
# one:
#    id:
#    user_name:
#    user_number:
#    last_name:
#    first_name:
#    status:
#    role:
#    created_at: <% Time.now.to_s(:db) %>
#    updated_at: <% Time.now.to_s(:db) %>

admin1:
    user_name:      man	
    last_name:      Manarin      
    first_name:     Amanda
    role:           admin

admin2:
    user_name:      a
    last_name:      Admin      
    first_name:     Mr
    role:           admin

admin3:
    user_name:      veve
    last_name:      Veronica      
    first_name:     Wong
    role:           admin

admin4:
    user_name:      Nelle
    last_name:      Varoquaux	     
    first_name:     Nelle
    role:           admin
