## Assignments development fixture

A1:
    name: A1
    description: Write Tests!
    message:
    due_date: <%= 1.hour.from_now.to_s(:db) %>

A2:
    name: A2
    description: Run Tests!
    message:
    due_date: <%= 3.days.from_now.to_s(:db) %>

A3:
    name: A3
    description: Write Code!
    message:
    due_date: <%= 3.weeks.from_now.to_s(:db) %>

A4:
    name: A4
    description: Run Code!
    message:
    due_date: <%= 3.months.from_now.to_s(:db) %>
