# Read about fixtures at http://ar.rubyonrails.org/classes/Fixtures.html

# User schema template:
#
# one:
#    id:
#    user_name:
#    user_number:
#    last_name:
#    first_name:
#    status:
#    role:
#    created_at: <% Time.now.to_s(:db) %>
#    updated_at: <% Time.now.to_s(:db) %>

admin1:
    user_name:      reid
    last_name:      Reid      
    first_name:     Karen
    role:           admin

admin2:
    user_name:      flaps
    last_name:      Rosenthal      
    first_name:     Alan
    role:           admin
    