#s1:
#  id:  1
#  grouping_id:  1
#  submission_version: 1
#  submission_version_used: true
#  revision_number: 4
#  revision_timestamp: <%= 1.hour.ago.to_s(:db) %>
  
#s2:
#  id:  2
#  grouping_id:  2
#  submission_version: 1
#  submission_version_used:  true
#  revision_number: 2
#  revision_timestamp: <%= 1.hour.ago.to_s(:db) %>
