# Read about fixtures at http://ar.rubyonrails.org/classes/Fixtures.html

# User schema template:
#
# one:
#    id:
#    user_name:
#    last_name:
#    first_name:
#    status:
#    role:
#    created_at: <% Time.now.to_s(:db) %>
#    updated_at: <% Time.now.to_s(:db) %>
#

admin1:
    user_name:      s	
    last_name:      Gehwolf      
    first_name:     Severin

admin2:
    user_name:      a
    last_name:      Admin      
    first_name:     Mr

admin3:
    user_name:      mike
    last_name:      Conley      
    first_name:     Mike

admin5:
    user_name:      karen
    last_name:      Reid
    first_name:     Karen

admin6:
    user_name:      Nelle
    last_name:      Varoquaux
    first_name:     nelle
